name: Check
on: push

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r req.txt
          pytest -vv src/test.py
  deploy:
    needs: [test]
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: |
          docker build . -t api-gateway
      - name: Deploy FastAPI
        run: |
          cd /home/server/Desktop/Api-gateway
          git pull
          docker run -p 8080:8080 api-gateway
